Algoritmo "exe1"
// Descrição   : vetor com 10 númeors e a soma de todos
// Autor(a)    : Rafaela Alves
// Data atual  : 01/11/2022
Var
num: vetor[0..9]de inteiro
cont,resul: inteiro


Inicio
para cont de 0 ate 9 faca
 escreval("Informe o ",cont+1," número")
 leia(num[cont])
 resul <- resul+num[cont]
fimpara

escreval("O resultado da soma dos 10 números é: ",resul)



Fimalgoritmo